package com.asura.greendao_study.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.asura.greendao_study.model.Picture;
import com.asura.greendao_study.model.User;

import com.asura.greendao_study.dao.PictureDao;
import com.asura.greendao_study.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pictureDaoConfig;
    private final DaoConfig userDaoConfig;

    private final PictureDao pictureDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pictureDaoConfig = daoConfigMap.get(PictureDao.class).clone();
        pictureDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        pictureDao = new PictureDao(pictureDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Picture.class, pictureDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        pictureDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public PictureDao getPictureDao() {
        return pictureDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
